<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Analyzers" />
    <PackageReference Include="Microsoft.Orleans.Server" />
    <ProjectReference Include="../../Comparison/Comparison.Contracts/Comparison.Contracts.csproj" />
    <ProjectReference Include="../Ordering.Grains/Ordering.Grains.csproj" />
    <ProjectReference Include="..\..\Hosting\Hosting.ServiceDefaults\Hosting.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Meziantou.Analyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
