<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <ProjectReference Include="../../Workbench/Workbench.Contracts/Workbench.Contracts.csproj" />
    <ProjectReference Include="..\..\Hosting\Hosting.ServiceDefaults\Hosting.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
