<Project>
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<NoWarn>$(NoWarn);CA1812;CA1711</NoWarn>
	</PropertyGroup>
</Project>
