<Project>
  <PropertyGroup>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
	<PackageVersion Include="coverlet.collector" Version="6.0.2" />
	<PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.11" />
	<PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
	<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
	<PackageVersion Include="Microsoft.Orleans.Server" Version="10.2.2" />
	<PackageVersion Include="Microsoft.Orleans.Sdk" Version="10.2.2" />
	<PackageVersion Include="Microsoft.Orleans.TestingHost" Version="10.2.2" />
	<PackageVersion Include="NSubstitute" Version="5.3.0" />
	<PackageVersion Include="Shouldly" Version="4.2.0" />
	<PackageVersion Include="xunit" Version="2.9.2" />
	<PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
