// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ordering.Persistence.Sqlite.Storage;

#nullable disable

namespace Ordering.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(GrainStateDbContext))]
    partial class GrainStateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Ordering.Persistence.Sqlite.Storage.GrainStateEntity", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrainType")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrainId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ServiceId", "ProviderName", "StateName", "GrainType", "GrainId");

                    b.ToTable("GrainStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
