<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Analyzers" />
    <PackageReference Include="Microsoft.Orleans.Runtime" />
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <ProjectReference Include="../../Comparison/Comparison.Contracts/Comparison.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Meziantou.Analyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
