<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Analyzers" />
    <PackageReference Include="Microsoft.Orleans.Runtime" />
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <ProjectReference Include="../../Workbench/Workbench.Contracts/Workbench.Contracts.csproj" />
  </ItemGroup>
</Project>
