<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Update="Meziantou.Analyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Observability\Observability.Health\Observability.Health.csproj" />
  </ItemGroup>
</Project>
