<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
		<PackageReference Include="Microsoft.Orleans.Runtime" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="Meziantou.Analyzer">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>
				runtime; build; native; contentfiles; analyzers; buildtransitive
			</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
