<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UserSecretsId>453bac7f-3ac8-4763-b909-31b542984930</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Workbench\Workbench.Contracts\Workbench.Contracts.csproj" IsAspireProjectResource="false" />
		<ProjectReference Include="..\..\Workbench\Workbench.Gateway\Workbench.Gateway.csproj" />
		<ProjectReference Include="..\..\Workbench\Workbench.Ui\Workbench.Ui.csproj" />
		<ProjectReference Include="..\..\Microservices\Inventory.Api\Inventory.Api.csproj" />
		<ProjectReference Include="..\..\Microservices\Orders.Api\Orders.Api.csproj" />
		<ProjectReference Include="..\..\Microservices\Payments.Api\Payments.Api.csproj" />
		<ProjectReference Include="..\..\VirtualActors\Ordering.Api\Ordering.Api.csproj" />
		<ProjectReference Include="..\..\VirtualActors\Ordering.Silo\Ordering.Silo.csproj" />
	</ItemGroup>

</Project>
